### PR TITLE
the virtual command has changed too.

### PR DESCRIPTION
**Pull request by lauraerinmann**
Might want to review http://virtualenv.readthedocs.org/en/latest/userguide.html.  I think the activate script is also slightly different.

### CODE REVIEW

**Comment by agconti** [comment]
Hey @lauraerinmann, thanks for checking this. 

They're actually the same commands. The writer of the virtualenv docs is just choosing to name his/her virtual environment folder `ENV` instead of a lowercase `env`. The name can be actually be anything; its all down to your own preference at the end of the day.

It's standard practice in the python community to use the lowercase version, so much so that its even included in the standard python [`.gitignore`](https://github.com/github/gitignore/blob/96ad0e39a54c7518a0dae8c77a8268a63cfe4a6e/Python.gitignore#L11) that GitHub provides. For those reasons, I'll keep the `virtualenv env` command in the readme. 

Thank you for your contributions!

**Comment by lauraerinmann** [comment]
Hey Andrew,
Maybe I have to take another look but I think the spelling of virtual in the command was different.  I'm a bit over worked its equally likely that I'm wrong.  I'll be toying around with the notebook hopefully I'll commit some more interesting stuff than documentation!

On January 23, 2016, at 5:52 PM, Andrew Conti <notifications@github.com> wrote:

Hey @lauraerinmann, thanks for checking this. 

They're actually the same commands. The writer of the virtualenv docs is just choosing to name his/her virtual environment folder ENV instead of a lowercase env. The name can be actually be anything; its all down to your own preference at the end of the day.

It's standard practice in the python community to use the lowercase version, so much so that its even included in the standard python .gitignore that GitHub provides. For those reasons, I'll keep the virtualenv env command in the readme. 

Thank you for your contributions!

**Comment by lauraerinmann** [comment]
yeah, I think the command is incorrect virturalenv  vs. virtualenv

**Comment by lauraerinmann** [comment]
virturalenv virtualenv

**Comment by agconti** [comment]
@lauraerinmann thanks for catching this. I thought you mean `ENV` vs `env`!

**Pull request closed without merging**
